apiVersion: v1
kind: PersistentVolume
metadata:
  name: music
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: unique-volumeid1  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//192.168.2.27/g/Meine Daten/Musik/Playlisten/Soundcloud"
    nodeStageSecretRef:
      name: smbcreds
      namespace: csi-smb-system