name: Build and Push Docker Image

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
        uses: 3deep5me/build-push-action@main
        with:
          image-name: scdl

          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish-dockerhub: false
          publish-ghcr: true